/*
* Libraries
*/
#include <WiFi.h>
#include <PubSubClient.h>
#include <ArduinoJson.h>

/*
* Network
*/
const char* ssid = "Antonio_Garrido_agb00094";
const char* password = "agb00094";
const char* mqtt_server = "10.3.141.75";
const int mqtt_port = 1883;
const char* mqtt_topic = "sensor/flow";

WiFiClient espClient;
PubSubClient client(espClient);

/*
* Sensors
*/
const int sensorPins[] = {13, 12, 14};
volatile long pulseCounts[3] = {0, 0, 0};
const float calibrationFactor = 7.5; // pulses per liter
unsigned long lastMillis = 0;
const unsigned long SEND_INTERVAL = 500;

// Interrupt Service Routines (ISRs) to count flow sensor pulses asynchronously
void IRAM_ATTR pulseCounter1() { pulseCounts[0]++; }
void IRAM_ATTR pulseCounter2() { pulseCounts[1]++; }
void IRAM_ATTR pulseCounter3() { pulseCounts[2]++; }

// Establishes connection to the specified local Wi-Fi access point
void setup_wifi() {
  Serial.print("Conectando a ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("\nWiFi conectado.");
  Serial.print("IP: ");
  Serial.println(WiFi.localIP());
}

// Reconnects to the MQTT broker using a dynamically generated randomized client ID
void reconnect() {
  while (!client.connected()) {
    String clientId = "ESP32_Flow_Station_" + String(random(0xffff), HEX);
    if (client.connect(clientId.c_str())) {
      Serial.println("Conectado al broker MQTT.");
    } else {
      Serial.print("Fallo al conectar MQTT, rc=");
      Serial.println(client.state());
      delay(3000);
    }
  }
}

void setup() {
  Serial.begin(115200);
  delay(500);


  /////////////////////////////////////////////////////////////////////   SENSORS CONFIG   /////////////////////////////////////////////////////////////////////
  // Initialize digital pins as input with internal pull-ups enabled
  for (int i = 0; i < 3; i++) {
    pinMode(sensorPins[i], INPUT_PULLUP);
  }

  // Stablishing of asyncronous functions in order to capture the pulses generated by the hall effect sensor
  // FALLING , as it is a pull-up config. 
  attachInterrupt(digitalPinToInterrupt(sensorPins[0]), pulseCounter1, FALLING);
  attachInterrupt(digitalPinToInterrupt(sensorPins[1]), pulseCounter2, FALLING);
  attachInterrupt(digitalPinToInterrupt(sensorPins[2]), pulseCounter3, FALLING);

  /////////////////////////////////////////////////////////////////////              /////////////////////////////////////////////////////////////////////
  setup_wifi();
  client.setServer(mqtt_server, mqtt_port);
  client.setBufferSize(1024); // ExpandS MQTT payload buffer size to handle the structured JSON array

}

void loop() {

  if (WiFi.status() != WL_CONNECTED) {
    setup_wifi();
  }

  if (!client.connected()) {
    reconnect();
  }

  // MQTT Library function to Keep-Alive the connection
  client.loop();

  unsigned long currentMillis = millis();
  // Non-blocking execution timer checking if the send interval has passed
  if (currentMillis - lastMillis >= SEND_INTERVAL) {
    unsigned long duration = currentMillis - lastMillis;
    lastMillis = currentMillis;

    StaticJsonDocument<512> doc;
    JsonArray sensores = doc.createNestedArray("sensores");

    // Process and calculate values for each of the 3 flow sensors
    for (int i = 0; i < 3; i++) {
      // Temporarily detach interrupts to read/write shared variables safely
      
      /*
      It is necessary to do this tecnique because it could happend this situation: The processor is reading the second byte of the long variable ' long pulses ' ; whenever a water flow is coming again, the variable shall change 
      the variable ' pulse ' in  the middle of the process the processor is reading it , so , the data will be corrupted.
      */

      //////////////////////////////////////////////////////////////////////

      noInterrupts();
      long pulses = pulseCounts[i];
      pulseCounts[i] = 0; // Reset pulse accumulator for the next cycle
      interrupts();

      float flowRate = 0.0;
      if (duration > 0) {
        // Formula converts raw pulses gathered in a time delta to Liters per Minute (L/min)
        flowRate = (pulses * 60000.0) / (duration * calibrationFactor);
      }

      // Check and sanitize against mathematical anomalies (Not-a-Number or Infinity)
      if (isnan(flowRate) || isinf(flowRate)) {
        flowRate = 0.0;
      }

      // Append data node to the JSON array, rounding the flow rate to two decimal points
      JsonObject sensor = sensores.createNestedObject();
      sensor["id"] = i + 1;
      sensor["flowRate"] = round(flowRate * 100.0) / 100.0;

      //////////////////////////////////////////////////////////////////////

    }


    char buffer[512];
    serializeJson(doc, buffer);

    // Ship the fully serialized payload string over the MQTT protocol
    if (client.publish(mqtt_topic, buffer)) {
      Serial.print("MQTT publicado: ");
      Serial.println(buffer);
    } else {
      Serial.println("Error publicando MQTT");
    }
  }
}